// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUl46zvLBJU13F6mvKzRnqrUalWnzygI',
    appId: '1:1041591250854:web:d2a1992b6e0b5c5324a967',
    messagingSenderId: '1041591250854',
    projectId: 'todolistapp-3f4bb',
    authDomain: 'todolistapp-3f4bb.firebaseapp.com',
    storageBucket: 'todolistapp-3f4bb.appspot.com',
    measurementId: 'G-BERYQ6G10K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFgbGNWnyGGmZObDe8oslwV5oG5ADaFK0',
    appId: '1:1041591250854:android:ca9242bd0d9ec26224a967',
    messagingSenderId: '1041591250854',
    projectId: 'todolistapp-3f4bb',
    storageBucket: 'todolistapp-3f4bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGOQh6sTGvJmWcqk1gQ91QtLb4sANOQg8',
    appId: '1:1041591250854:ios:91f8bf7e460baadb24a967',
    messagingSenderId: '1041591250854',
    projectId: 'todolistapp-3f4bb',
    storageBucket: 'todolistapp-3f4bb.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGOQh6sTGvJmWcqk1gQ91QtLb4sANOQg8',
    appId: '1:1041591250854:ios:91f8bf7e460baadb24a967',
    messagingSenderId: '1041591250854',
    projectId: 'todolistapp-3f4bb',
    storageBucket: 'todolistapp-3f4bb.appspot.com',
    iosBundleId: 'com.example.todolistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEUl46zvLBJU13F6mvKzRnqrUalWnzygI',
    appId: '1:1041591250854:web:d98ccae7a06365d124a967',
    messagingSenderId: '1041591250854',
    projectId: 'todolistapp-3f4bb',
    authDomain: 'todolistapp-3f4bb.firebaseapp.com',
    storageBucket: 'todolistapp-3f4bb.appspot.com',
    measurementId: 'G-M695P4ZN6S',
  );

}